# Generated by Django 5.2.8 on 2025-11-16 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0002_uielement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='queued', max_length=32)),
                ('actual_screenshot', models.ImageField(blank=True, null=True, upload_to='runs/')),
                ('details', models.TextField(blank=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='testsystem.testcase')),
            ],
        ),
    ]
